merge_protections:
  - name: Do not merge outdated PRs
    description: Make sure PRs are almost up to date before merging
    if:
      - base = main
    success_conditions:
      - "#commits-behind <= 3"
queue_rules:
  - name: Default
    merge_method: squash
    checks_timeout: 54 m 21 s
    max_check_retries: 2
    update_method: rebase
merge_queue:
  max_parallel_checks: 1
pull_request_rules:
  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label automerge
    conditions:
      - label = automerge
    actions:
      merge:
  - name: Make sure PR are up to date before merging with rebase
    description: This automatically rebases PRs when they are out-of-date with the
      base branch to avoid semantic conflicts (next step is using a merge
      queue).
    conditions: []
    actions:
      rebase:
