merge_protections:
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - base = main
    success_conditions:
      - "title ~=
        ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\
        \\))?:"
  - name: Do not merge outdated PRs
    description: Make sure PRs are almost up to date before merging
    if:
      - base = main
    success_conditions:
      - "#commits-behind <= 3"
queue_rules:
  - name: Default
    merge_method: squash
    checks_timeout: 54 m 21 s
    max_check_retries: 2
    update_method: rebase
merge_queue:
  max_parallel_checks: 1
